### ISSUE TITLE
Pressing CTRL-C in the telnet client stops all output.

### ISSUE THREAD

**Issue by icculus** [icculus/mojozork#1]
Might be a telnet thing, I dunno. Look into this.

**Comment by scandum** [comment]
It's a telnet thing since you're operating on port 23.

If memory serves me right, telnet will send IAC DO TIMING_MARK on ctrl-c, and you can get it to unlock with the server sending back IAC WONT TIMING_MARK.

In hex that's \xFF\xFD\x06 and the response is \xFF\xFE\x06
