### ISSUE TITLE
ERROR: parse buffer is too small for reading (mojozork.c)

### ISSUE THREAD

**Issue by fletcher** [icculus/mojozork#24]
I apologize if this issue is out of scope for the project.

I attempted to play a couple of z3 games, and one of them was Moonmist (I tried both moonmist-r13-s880501.z3 and moonmist-r4-s860918.z3 from the Obsessively Complete Infocom Catalog.)

The following sequence leads to the parse buffer error:

    push eye
    Mr John Doe

I am still trying to understand the source code, but when I change the condition in line 1336 of mojozork.c to be `if (parselen < 3)` instead of `if (parselen < 4)`, then these actions work correctly, and I can continue the game.

I am not sure what I may have broken by doing this.  As a quick check, I ran `./mojozork zork1.dat zork1-script.txt` and it successfully completed the game without any apparent errors.  I realize this is not a comprehensive validation that I did not break something else here, since I assume that condition was placed for a purpose.

Is there a proper solution for this parsing error in Moonmist?

Thank you for your thoughts, as well as for this project!

**Comment by icculus** [comment]
This was my mistake, sorry about that! Should work now.

**Comment by fletcher** [comment]
Thanks for the quick fix!!
